blank_issues_enabled: false
contact_links:
  - name: 💬 Dúvidas ou Ideias Gerais
    url: https://github.com/realkalashnikov/transcriber/discussions
    about: Pergunte e compartilhe ideias com a comunidade.
